# Max Levels for Enchants (replaces vanilla defaults)
max-levels:
  power: 5
  flame: 1
  infinity: 1
  punch: 2
  binding: 1
  channeling: 1
  sharpness: 1
  bane_of_arthropods: 5
  smite: 5
  depth_strider: 3
  efficiency: 5
  unbreaking: 3
  fire_aspect: 2
  frost_walker: 2
  impaling: 5
  knockback: 2
  fortune: 3
  looting: 3
  loyalty: 3
  luck_of_the_sea: 3
  lure: 3
  mending: 1
  multishot: 1
  respiration: 3
  piercing: 4
  protection: 4
  blast_protection: 4
  feather_falling: 4
  fire_protection: 4
  projectile_protection: 4
  quick_charge: 3
  riptide: 3
  silk_touch: 1
  sweeping_edge: 3
  thorns: 3
  vanishing: 1
  aqua_affinity: 1


# Assumed maximum if not explicitly listed above
# Use -1 for default vanilla maximums
default-max: -1

# Use old (1.3.1-1.7.10) enchanting mechanics:
# Consumes 30 levels, but doesn't require lapis.
old-enchanting-behavior: false

# Enable anvil config features (required for everything below here)
enable-anvil-features: true

# Allow players to put mending AND infinity on bows again (1.9-1.11.1)
mending-and-infinity-bows: true

# Allow players to put multiple protection enchants on the same armor piece (1.14-1.14.2)
multiple-protection-types: true

looting-on-axe: true
fire-aspect-on-axe: true
sharpness-on-pickaxe: true
looting-on-pickaxe: true
fire-aspect-on-pickaxe: true
sharpness-on-shovel: true
looting-on-shovel: true
fire-aspect-on-shovel: true
sharpness-on-hoe: true
looting-on-hoe: true
fire-aspect-on-hoe: true
silk-touch-on-sword: true