name: EnchantBook
main: net.evmodder.EnchantBook.EnchantBook
Author: EvModder
version: 3.0 #3.0=1.14 rewrite

commands:
   combinebooks:
      description: Merge matching enchantments on enchanted books
      usage: /combine-all
      aliases: [combine,combine-all,onebook,fullbook]
      permission: enchantbook.combine
      permission-message: You do not have permission to do this.

   separatebooks:
      description: Split enchantments onto separate books
      usage: /separate
      aliases: [separate,separate-ench,cut-all,sepbooks,splitbooks,splitench,sepench,split-ench]
      permission: enchantbook.separate
      permission-message: You do not have permission to do this.

   enchant:
      description: Enchant the item in your hand
      usage: /ench <name>:<level/int_max/vanilla_max/config_max> ...
      aliases: [evchant,bookenchant,itemenchant,ench,addenchant]
      permission: enchantbook.enchant
      permission-message: You do not have permission to do this.

permissions:
   enchantbook.combine:
      description: Combine books with the command /combine-all.
      default: op

   enchantbook.separate:
      description: Separate stored book enchantments with the command /separate
      default: op

   enchantbook.separate.free:
      description: Separate enchanted books without consuming regular books
      default: false

   enchantbook.separate.all:
      description: Separate all enchanted books in inventory (instead of just in hand)
      default: op

   enchantbook.enchant:
      description: Ability to enchant items with /enchant.
      default: op

   enchantbook.abovenatural:
      description: Ability to enchant items above the natural maximum level
      children:
         enchantbook.enchant.abovenatural: true
         enchantbook.combine.abovenatural: true
         enchantbook.anvil.abovenatural: true
      default: op

   enchantbook.aboveconfig:
      description: Ability to enchant items to higher levels then in the config
      children:
         enchantbook.enchant.aboveconfig: true
         enchantbook.combine.aboveconfig: true
         enchantbook.anvil.aboveconfig: true
      default: op

   enchantbook.conflicting:
      description: Ability add conflicting enchantments to an item.
      children:
         enchantbook.enchant.conflicting: true
         enchantbook.anvil.conflicting: true
      default: op

   enchantbook.anyitem:
      description: Ability add enchantments to any item (such as hoes, blocks, etc)
      children:
         enchantbook.enchant.anyitem: true
         enchantbook.anvil.anyitem: true
      default: op

   enchantbook.anvil.color:
      description: Add colors when naming an item on an anvil.
      default: true
      children:
         enchantbook.anvil.color.aqua: true
         enchantbook.anvil.color.black: true
         enchantbook.anvil.color.blue: true
         enchantbook.anvil.color.dark_aqua: true
         enchantbook.anvil.color.dark_blue: true
         enchantbook.anvil.color.dark_gray: true
         enchantbook.anvil.color.dark_green: true
         enchantbook.anvil.color.dark_purple: true
         enchantbook.anvil.color.dark_red: true
         enchantbook.anvil.color.gold: true
         enchantbook.anvil.color.gray: true
         enchantbook.anvil.color.green: true
         enchantbook.anvil.color.light_purple: true
         enchantbook.anvil.color.red: true
         enchantbook.anvil.color.reset: true
         enchantbook.anvil.color.white: true
         enchantbook.anvil.color.yellow: true

   enchantbook.anvil.format:
      description: Add formats when naming an item on an anvil.
      default: true
      children:
         enchantbook.anvil.format.bold: true
         enchantbook.anvil.format.italic: true
         enchantbook.anvil.format.magic: true
         enchantbook.anvil.format.reset: true
         enchantbook.anvil.format.strikethrough: true
         enchantbook.anvil.format.underline: true