name: EnchantBook
main: Evil_Code_EnchantBook.EnchantBook
Author: EvModder
version: 2.4
api-version: 1.13

commands:
   combineall:
      description: Combine matching enchants on enchanted books
      usage: /combine-all
      aliases: [combbinebooks,combine-all,onebook,fullbook]
      permission: evp.evchant.combinebooks
      permission-message: You do not have permission to do this.

   separate:
      description: Split enchantments onto separate books
      usage: /separate
      aliases: [separate-ench,cut-all,sepbooks,splitbooks,splitench,sepench,split-ench]
      permission: evp.evchant.separate
      permission-message: You do not have permission to do this.

   enchant:
      description: Enchant the item you are holding to the level you specify
      usage: /ench [name,name2,ID,all] [level/minecraft-max/config-max/natural-max] -[applicable:true/false]
      aliases: [evchant,bookenchant,itemenchant,ench,addenchant]
      permission: evp.evchant.command.enchant
      permission-message: You do not have permission to do this.

permissions:
   evp.evchant.command.enchant:
        description: Ability to enchant items with /enchant.
        default: op

   evp.evchant.combinebooks:
        description: Combine books with the command /combine-all.
        default: op

   evp.evchant.separate:
        description: Separate stored book enchantments with the command /separate
        default: op

   evp.evchant.separate.free:
        description: Separate enchanted-books without the requirement to have unenchanted books in your inventory
        default: false

   evp.evchant.anvil:
        description: Permission to use anvils
        default: true
        
   evp.evchant.anvil.color:
        description: Give an item a colored name on an anvil.
        default: false

   evp.evchant.unrestricted:
        description: Unrestricted enchantment manipulation
        children:
            evp.evchant.combine.unrestricted: true
            evp.evchant.anvil.unrestricted: true
            evp.evchant.command.unrestricted: true
            evp.evchant.abovenatural: true
            evp.evchant.conflicting: true
        default: false

   evp.evchant.aboveconfig:
        description: Ability to get enchantments higher then allowed in the config.
        children:
            evp.evchant.combine.aboveconfig: true
            evp.evchant.anvil.aboveconfig: true
            evp.evchant.command.aboveconfig: true
        default: op

   evp.evchant.abovenatural:
        description: Ability to enchant items above the natural maximum
        children:
            evp.evchant.combine.abovenatural: true
            evp.evchant.anvil.abovenatural: true
            evp.evchant.command.abovenatural: true
        default: op

   evp.evchant.conflicting:
        description: Ability add conflicting enchantments to an item.
        children:
            evp.evchant.anvil.conflicting: true
            evp.evchant.command.conflicting: true
        default: op

   evp.evchant.anyitem:
        description: Ability add enchantments to any item (such as hoes, blocks, etc)
        children:
            evp.evchant.anvil.anyitem: true
            evp.evchant.command.anyitem: true
        default: op